version : "3.8"

services:
  frontend:
    build : 
      context: ./Frontend/.
    networks : 
      - blog
    depends_on:
      - backend

    ports : 
      - "3000:3000"
    restart : always
     

  backend:
    
    build: 
      context : ./backend/.
  
    networks:
      - blog
    ports:
      - "3005:3005"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005"]  
      interval: 10s
      timeout : 5s
      retries: 5
      start_period: 60s 
    
networks:
  blog:
    driver: bridge
